pipeline {
   agent any
   triggers {
      pollSCM('*/1 * * * *')
   }
   environment{
          DOCKER_IMAGE = 'gateway'
          DOCKER_TAG = "${env.BUILD_NUMBER}"
          DOCKER_REPO = 'killerquen69'

   }
   stages {
      stage('build stage') {
        when {
           changeset "gateway-microservice/**"
        }
        agent{
          docker {
             image 'gradle:8.14.0-jdk17'
          }
        }
        steps {
           dir('gateway-microservice') {
               sh 'gradle build -x test'
           }
        }
      }
      stage ('sca ') {
         when {
            changeset "gateway-microservice/**"
         }
         steps {
            dir('gateway-microservice') {
               dependencyCheck additionalArguments: '--format HTML', nvdCredentialsId: 'owasp', odcInstallation: 'DP-Check'
            }
         }
      }
      stage('sast') {
               when {
                  changeset "gateway-microservice/**"
               }
               agent {
                  docker {
                     image 'gradle:8.14.0-jdk17'
                     args '''
                          --network jenkins
                          --entrypoint=""
                          --user root
                          -v /var/run/docker.sock:/var/run/docker.sock
                          '''
                  }
               }
               steps{
                  dir('gateway-microservice') {
                       withSonarQubeEnv( installationName: 'sq1') {
                                       sh '''
                                          gradle test jacocoTestReport sonar \
                                                 -Dsonar.projectKey=jenkins \
                                                 -Dsonar.projectName='jenkins'
                                          '''
                       }
                  }
               }
      }
      stage('package stage') {
        when {
           changeset "gateway-microservice/**"
        }
        agent {
          docker {
             image 'docker:24.0-cli'
             args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
          }
        }
        steps{
           dir('gateway-microservice') {
              sh 'docker build -t $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG .'
           }

        }
      }
      stage('scan stage') {
         when {
            changeset "gateway-microservice/**"
         }
         agent {
            docker {
              image 'aquasec/trivy'
              args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
         steps {
            dir('gateway-microservice') {
                sh 'trivy image --no-progress --severity HIGH,CRITICAL --skip-files "*.jar" --timeout 20m $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG'
            }
         }
      }
      stage('push stage') {
         when {
            changeset "gateway-microservice/**"
         }
         agent {
            docker {
               image 'docker:24.0-cli'
               args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
         steps {
             dir('gateway-microservice') {

                withCredentials([usernamePassword(credentialsId: 'killerquen69', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

                       docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
                       '''
                }

             }

         }

      }
      stage ('deployment stage') {
         when {
            changeset "gateway-microservice/**"
         }
                steps {


                      withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {

                                sh '''
                                   git config --global user.email "hamza.elmalki1234@gmail.com"
                                   git config --global user.name "Hamzacherkaouiel"
                                   git config --global pull.rebase false
                                   git checkout master
                                   git pull origin master

                                   cd k8s
                                   sed -i "s|image: $DOCKER_REPO/$DOCKER_IMAGE:[^ ]*|image: $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG|g" gateway-microservice-deployment.yaml
                                   cat gateway-microservice-deployment.yaml
                                   git add .
                                   git commit -m "update manifest"
                                   git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/simoait02/PFA-INE2-ASEDS.git
                                   git push -u origin master
                                   '''
                      }



                }

      }
   }
}