version: '3'

services:
  database1:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - datauser:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  database2:
    image: postgres
    ports:
      - ${DB_PORT2}:5432
    volumes:
      - datauser2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME2}

  database3:
    image: postgres
    ports:
      - ${DB_PORT3}:5432
    volumes:
      - datauser3:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME3}

  VideoDatabase:
    image: mongo
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodata1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  StreamDatabase:
    image: mongo
    container_name: mongoStream
    ports:
      - ${MONGO_PORT2}:27017
    volumes:
      - mongodata2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  datauser:
    driver: local
  datauser2:
    driver: local
  datauser3:
    driver: local
  mongodata1:
    driver: local
  mongodata2:
    driver: local
