pipeline {
   agent none
   triggers {
      pollSCM('*/1 * * * *')
   }
   environment{
          DOCKER_IMAGE = 'blogs'
          DOCKER_TAG = "${env.BUILD_NUMBER}"
          DOCKER_REPO = 'killerquen69'

   }
   stages {
      stage('build stage') {
        agent{
          docker {
             image 'gradle:8.14.0-jdk21'
          }
        }
        steps {
           dir('blogs-microservice') {
               sh 'gradle build -x test'
               archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
           }

        }
      }
      stage('sast') {
               agent {
                  docker {
                     image 'gradle:8.14.0-jdk21'
                     args '''
                          --network jenkins
                          --entrypoint=""
                          --user root
                          -v /var/run/docker.sock:/var/run/docker.sock
                          '''
                  }
               }
               steps{
                  dir('blogs-microservice') {
                       withSonarQubeEnv( installationName: 'sq1') {
                                       sh '''
                                          gradle test jacocoTestReport sonar \
                                                 -Dsonar.projectKey=jenkins \
                                                 -Dsonar.projectName='jenkins'
                                          '''
                       }
                  }
               }
      }
      stage('package stage') {
        agent {
          docker {
             image 'docker:24.0-cli'
             args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
          }
        }
        steps{
           dir('blogs-microservice') {
              sh 'docker build -t $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG .'
           }

        }
      }
      stage('scan stage') {
         agent {
            docker {
              image 'aquasec/trivy'
              args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
         steps {
            dir('blogs-microservice') {
                sh 'trivy image --no-progress --severity HIGH,CRITICAL --skip-files "*.jar" --timeout 20m $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG'
            }
         }
      }
      stage('push stage') {

         agent {
            docker {
               image 'docker:24.0-cli'
               args '--entrypoint="" --user root -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
         steps {
             dir('blogs-microservice') {
                withCredentials([usernamePassword(credentialsId: 'killerquen69', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

                       docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
                       '''
                }
             }
         }
      }
   }
}