spring:
  application:
    name: userManagement-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/users
    username: postgres
    password: hamza
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ayFyjaxTLdllxt8GvjrBBwyYfyrayv9dclPJHK101kb9RIfrs2NdGi2WCPvV+Ok996aX8C/q8q8+X2KaHTkQtw==
  internal: djUPkee9MDnEZgT6hnMc7dAXKIO8J46VDfFkVajL9ADo6nd3TUJ9/yF/ca/dTPqSvtPBFmWmBzSPh/m0Mvi1yw==