apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-microservice
  namespace: twitch
  labels:
    app: blogs-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogs-microservice
  template:
    metadata:
      name: blogs-microservice
      labels:
        app: blogs-microservice
    spec:
      containers:
        - name: blogs-microservice
          image: killerquen69/blogs:2
          imagePullPolicy: Always
          env:
            - name: DATASOURCE_PORT
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_PORT
                  name: blogs-secret
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: blogs-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blogs-secret
                  key: DATASOURCE_PASSWORD
            - name: DATASOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: blogs-secret
                  key: DATASOURCE_NAME
            - name: HOST
              valueFrom:
                secretKeyRef:
                  key: HOST
                  name: blogs-secret
          ports:
            - containerPort: 8050
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: blogs-microservice-service
  namespace: twitch
  labels:
    app: blogs-microservice-service
spec:
  selector:
    app: blogs-microservice
  ports:
    - port: 8050
      targetPort: 8050

