apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-microservice
  namespace: twitch
  labels:
    app: channels-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: channels-microservice
  template:
    metadata:
      name: channels-microservice
      labels:
        app: channels-microservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "channels-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/channels"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/channels" -}}
          spring.datasource.url=jdbc:postgresql://{{ .Data.data.HOST }}:{{ .Data.data.DATASOURCE_PORT }}/{{ .Data.data.DATASOURCE_NAME }}
          spring.datasource.username={{ .Data.data.DATASOURCE_USERNAME }}
          spring.datasource.password={{ .Data.data.DATASOURCE_PASSWORD }}
          video.management.api.base-url={{ .Data.data.VIDEO_MANAGEMENT_API_BASE_URL }}
          {{- end }}
    spec:
      containers:
        - name: channels-microservice
          image: killerquen69/channels:22
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/vault/secrets/"
          ports:
            - containerPort: 8444
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: channels-microservice-service
  namespace: twitch
  labels:
    app: channels-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: channels-microservice
  ports:
    - port: 8444
      targetPort: 8444