apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-microservice
  namespace: twitch
  labels:
    app: channels-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: channels-microservice
  template:
    metadata:
      name: channels-microservice
      labels:
        app: channels-microservice
    spec:
      containers:
        - name: channels-microservice
          image: killerquen69/channels:2
          imagePullPolicy: Always
          env:
            - name: DATASOURCE_PORT
              valueFrom:
                secretKeyRef:
                  key: DATASOURCE_PORT
                  name: channels-secret
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: channels-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: channels-secret
                  key: DATASOURCE_PASSWORD
            - name: DATASOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: channels-secret
                  key: DATASOURCE_NAME
            - name: VIDEO_MANAGEMENT_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: channels-secret
                  key: VIDEO_MANAGEMENT_API_BASE_URL
            - name: HOST
              valueFrom:
                secretKeyRef:
                  key: HOST
                  name: channels-secrett
          ports:
            - containerPort: 8444
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: channels-microservice-service
  namespace: twitch
  labels:
    app: channels-microservice-service
spec:
  selector:
    app: channels-microservice
  ports:
    - port: 8444
      targetPort: 8444

