apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice
  namespace: twitch
  labels:
    app: gateway-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      name: gateway-microservice
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: killerquen69/gateway:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice-service
  namespace: twitch
  labels:
    app: gateway-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-microservice
  ports:
    - port: 8070
      targetPort: 8070