apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: twitch
  annotations:
    # ModSecurity Web Application Firewall
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"

    # Security settings
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

    # Rate limiting for DDoS protection - More restrictive for API Gateway
    nginx.ingress.kubernetes.io/rate-limit: "50"  # 50 requests per window
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"  # 1 minute window
    nginx.ingress.kubernetes.io/rate-limit-connections: "10"  # 10 concurrent connections per IP

    # Connection and timeout settings
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"

spec:
  ingressClassName: nginx
  rules:
    - host: api-gateway.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-microservice-service
                port:
                  number: 8070
