apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: twitch
data:
  database: streams

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-stream
  namespace: twitch
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongo-stream

---
apiVersion: v1
kind: Service
metadata:
  name: stream-database-service
  namespace: twitch
spec:
  selector:
    app: mongo-stream
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-stream
  namespace: twitch
spec:
  serviceName: "mongo-stream"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-stream
  template:
    metadata:
      labels:
        app: mongo-stream
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "stream-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-MONGO_USER: "secret/data/stream"
        vault.hashicorp.com/agent-inject-template-MONGO_USER: |
          {{- with secret "secret/data/stream" -}}
          {{ .Data.data.mongo_user }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-MONGO_PASSWORD: "secret/data/stream"
        vault.hashicorp.com/agent-inject-template-MONGO_PASSWORD: |
          {{- with secret "secret/data/stream" -}}
          {{ .Data.data.mongo_password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-MONGO_DB: "secret/data/stream"
        vault.hashicorp.com/agent-inject-template-MONGO_DB: |
          {{- with secret "secret/data/stream" -}}
          {{ .Data.data.mongo_db }}
          {{- end }}
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: "/vault/secrets/mongo_user"
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: "/vault/secrets/mongo_password"
            - name: MONGO_INITDB_DATABASE_FILE
              value: "/vault/secrets/mongo_db"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
