apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-microservice
  namespace: twitch
  labels:
    app: stream-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-microservice
  template:
    metadata:
      name: stream-microservice
      labels:
        app: stream-microservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "stream-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/stream"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/stream" -}}
          spring.data.mongodb.uri=mongodb://{{ .Data.data.mongo_user }}:{{ .Data.data.mongo_password }}@{{ .Data.data.host }}:{{ .Data.data.mongo_port }}/{{ .Data.data.mongo_db }}?authSource=admin
          nginx.rtmp={{ .Data.data.nginx_rtmp }}
          {{- end }}
    spec:
      containers:
        - name: stream-microservice
          image: simo3011w/twitch-stream-microservice
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/vault/secrets/"
          ports:
            - containerPort: 8085
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stream-microservice-service
  namespace: twitch
  labels:
    app: stream-microservice-service
spec:
  selector:
    app: stream-microservice
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 32002
  type: NodePort