apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: twitch
data:
  database: users

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-users
  namespace: twitch
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: users-postgres
  selector:
    app: postgres-users

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-users
  namespace: twitch
spec:
  serviceName: "postgres-blogs"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "user-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-POSTGRES_USER: "secret/data/usermanagement"
        vault.hashicorp.com/agent-inject-template-POSTGRES_USER: |
          {{- with secret "secret/data/usermanagement" -}}
          {{ .Data.data.DATASOURCE_USERNAME }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-POSTGRES_PASSWORD: "secret/data/usermanagement"
        vault.hashicorp.com/agent-inject-template-POSTGRES_PASSWORD: |
          {{- with secret "secret/data/usermanagement" -}}
          {{ .Data.data.DATASOURCE_PASSWORD }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-POSTGRES_DB: "secret/data/usermanagement"
        vault.hashicorp.com/agent-inject-template-POSTGRES_DB: |
          {{- with secret "secret/data/usermanagement" -}}
          {{ .Data.data.DATASOURCE_NAME }}
          {{- end }}
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER_FILE
              value: "/vault/secrets/postgres_user"
            - name: POSTGRES_PASSWORD_FILE
              value: "/vault/secrets/postgres_password"
            - name: POSTGRES_DB_FILE
              value: "/vault/secrets/postgres_db"
          volumeMounts:
            - name: postgres-users
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-users
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi