apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-microservice
  namespace: twitch
  labels:
    app: usermanagement-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement-microservice
  template:
    metadata:
      name: usermanagement-microservice
      labels:
        app: usermanagement-microservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "user-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/usermanagement"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/usermanagement" -}}
          spring.datasource.url=jdbc:postgresql://{{ .Data.data.HOST }}:{{ .Data.data.DATASOURCE_PORT }}/{{ .Data.data.DATASOURCE_NAME }}
          spring.datasource.username={{ .Data.data.DATASOURCE_USERNAME }}
          spring.datasource.password={{ .Data.data.DATASOURCE_PASSWORD }}
          jwt.secret={{ .Data.data.JWT_SECRET }}
          jwt.internal={{ .Data.data.JWT_INTERNAL }}
          {{- end }}
    spec:
      containers:
        - name: usermanagement-microservice
          image: killerquen69/usermangement:1
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/vault/secrets/"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: usermanagement-microservice-service
  namespace: twitch
  labels:
    app: usermanagement-microservice-service
spec:
  type: ClusterIP
  selector:
    app: usermanagement-microservice
  ports:
    - port: 8080
      targetPort: 8080