apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-microservice
  namespace: twitch
  labels:
    app: video-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-microservice
  template:
    metadata:
      name: video-microservice
      labels:
        app: video-microservice
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "video-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/video"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/video" -}}
          spring.data.mongodb.uri=mongodb://{{ .Data.data.mongo_user }}:{{ .Data.data.mongo_password }}@{{ .Data.data.host }}:{{ .Data.data.mongo_port }}/{{ .Data.data.mongo_db }}?authSource=admin
          channel.management.api.base-url={{ .Data.data.channel_management_api_base_url }}
          jwt.secret={{ .Data.data.jwt_secret }}
          jwt.internal={{ .Data.data.jwt_internal }}
          {{- end }}
    spec:
      containers:
        - name: video-microservice
          image: simo3011w/twitch-video-microservice
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/vault/secrets/"
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: video-microservice-service
  namespace: twitch
  labels:
    app: video-microservice-service
spec:
  selector:
    app: video-microservice
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer