apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: twitch
data:
  database: videos

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-video
  namespace: twitch
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongo-video

---
apiVersion: v1
kind: Service
metadata:
  name: video-database-service
  namespace: twitch
spec:
  selector:
    app: mongo-video
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-video
  namespace: twitch
spec:
  serviceName: "mongo-video"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-video
  template:
    metadata:
      labels:
        app: mongo-video
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "video-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/video"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/video" -}}
          MONGO_INITDB_ROOT_USERNAME={{ .Data.data.mongo_user }}
          MONGO_INITDB_ROOT_PASSWORD={{ .Data.data.mongo_password }}
          MONGO_INITDB_DATABASE={{ .Data.data.mongo_db }}
          {{- end }}
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: "/vault/secrets/application.properties"
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: "/vault/secrets/application.properties"
            - name: MONGO_INITDB_DATABASE_FILE
              value: "/vault/secrets/application.properties"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
