apiVersion: v1
kind: Secret
metadata:
  name: video-microservice-secret
  namespace: twitch

type: Opaque
stringData:
  mongo_port: "27017"
  mongo_user: "simo"
  mongo_password: "simo"
  mongo_db: "videos"
  jwt_secret: "ayFyjaxTLdllxt8GvjrBBwyYfyrayv9dclPJHK101kb9RIfrs2NdGi2WCPvV+Ok996aX8C/q8q8+X2KaHTkQtw=="
  jwt_internal: "djUPkee9MDnEZgT6hnMc7dAXKIO8J46VDfFkVajL9ADo6nd3TUJ9/yF/ca/dTPqSvtPBFmWmBzSPh/m0Mvi1yw=="
  channel_management_api_base_url: "http://localhost:8444/channels/"
  host: "video-database-service"

