spring:
  application:
    name: stream-microservice
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin

nginx:
  rtmp: ${NGINX_RTMP}
server:
  port: 8085