spring:
  application:
    name: gateway-microservice
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: ${ROUTES_USER_AUTH_ID}
          uri: ${ROUTES_USER_AUTH_URI}
          predicates:
            - Path=/api/**
        - id: ${ROUTES_USER_MANAGEMENT_ID}
          uri: ${ROUTES_USER_MANAGEMENT_URI}
          predicates:
            - Path=/user-management/**
        - id: ${ROUTES_CHANNEL_ID}
          uri: ${ROUTES_CHANNEL_URI}
          predicates:
            - Path=/channels/**
server:
  port: 8070
