spring:
  application:
    name: channels-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
video:
  management:
    api:
      base-url: ${VIDEO_MANAGEMENT_API_BASE_URL}


server:
  port: 8444