spring:
  application:
    name: video-microservice
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_DB}?authSource=admin

server:
  port: 8081

user:
  management:
    api:
      base-url: ${USER_MANAGEMENT_API_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  internal: ${JWT_INTERNAL}