spring:
  application:
    name: video-microservice
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_DB}?authSource=admin

server:
  port: 8081

channel:
  management:
    api:
      base-url: ${CHANNEL_MANAGEMENT_API_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  internal: ${JWT_INTERNAL}

